name: Build and publish a Docker image to ghcr.io
on:

  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v3'
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: _json_key
          password: ${{ secrets.GCR_REGISTRY_TOKEN }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v3
        with:
          push: true
          file: Dockerfile
          tags:
            ghcr.io/simonfrey/${{ github.repository }}:${{ github.sha }}
